apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exception-api-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rGarmendia/argo-python-config.git
    targetRevision: HEAD
    path: exception-api/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: exception-api
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true